CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  user_id uuid NOT NULL,
  amount NUMERIC(14, 2) NOT NULL,
  type VARCHAR NOT NULL,
  is_blocked BOOL NOT NULL DEFAULT false
);