server:
  port: 8181
  servlet:
    context-path: /api/v2/loans

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    host: localhost
    port: 5435
    dbName: loans_db
    username: loans_dev
    password: loans_dev
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbName}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
  override-with-generic-response: false

loans:
  scheduling:
    pool:
      size: 4
      prefix: loans-reminder