server:
  port: 8181
  servlet:
    context-path: /api/v2/loans

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0