server:
  servlet:
    context-path: /api/v2/users
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    host: localhost
    port: 5434
    dbName: auth_db
    username: auth_dev
    password: auth_dev
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbName}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
  override-with-generic-response: false